### ISSUE TITLE
Few more issues in library

### ISSUE THREAD

**Issue by xmenxwk** [Protocentral/Protocentral_ADS1220#2]
- Do not use Serial in your library without a debug boolean set to false, anyone using the serial for something else, might get the unexpected data.
- Hard coding ADS1220_CS_PIN and ADS1220_DRDY_PIN is not a good idea. Use constructor to get these pin values. 
- There is no way to read single pin input.

**Comment by awhitchurch** [comment]
Thank you @xmenxwk , we are correcting this and all other issues in the new release of the library
