### ISSUE TITLE
Bad NewDataAvailable test in example/Basic

### ISSUE THREAD

**Issue by JRDavisUF** [Protocentral/Protocentral_ADS1220#4]
There is an issue in  Protocentral_ADS1220/Libraries/examples/Basic/Protocentral_ADS1220.ino
which causes values to be output as "new" samples when they are *not* new.

Currently line 54 is:
if(ADS1220.NewDataAvailable = true)

This is not actually a test, it just assigns the ADS1220.NewDataAvailable flag to true.  As such, this test statement always evaluates as true and a value is taken from the pointer and output to the screen as if it were a fresh ADC conversion.

This line should be
if(ADS1220.NewDataAvailable == true)

You can see this problem if you setup continuous sampling using the default 20pps and then try to sample faster than that.  For example, replace the delay(300) with delay (10).

**Comment by awhitchurch** [comment]
Thank you @JRDavisUF , we are in the process of creating a new library for this part.
